---
- Utilities:
    - Actual:
        icon: actual-budget.png
        href: https://actual.fantaquoggio.bid
        description: Gestisce i sordi
        server: server-docker
        container: actualbudget
        statusStyle: "dot"
        showStats: true

    - Trilium:
        icon: trilium.png
        href: http://quoggioserver:5050
        description: Note taking app
        server: server-docker
        container: trilium
        statusStyle: "dot"
        showStats: true

    - pihole:
        icon: pi-hole.png
        href: https://pihole.fantaquoggio.bid/admin
        description: adblocker definitivo
        server: server-docker
        container: pihole
        statusStyle: "dot"
        showStats: true

    - zerobyte:
        icon: zerobyte.png
        href: http://quoggioserver:4096
        description: backup
        server: server-docker
        container: zerobyte
        statusStyle: "dot"
        showStats: true

    - beszel:
        icon: beszel.png
        href: http://quoggioserver:8090
        description: monitoring
        server: server-docker
        container: beszel
        statusStyle: "dot"
        showStats: true

    - qBitTorrent:
        icon: qbittorrent.png
        href: http://quoggioserver:8585
        description: Attento ai pornazzi
        server: server-docker
        container: qbittorrent
        statusStyle: "dot"
        showStats: true

    - nginx-proxy-manager:
        icon: nginx-proxy-manager.png
        href: http://quoggioserver:81
        description: nginx-proxy-manager
        server: server-docker
        container: proxy
        statusStyle: "dot"
        showStats: true

    - Mealie:
        icon: mealie.png
        href: https://mealie.fantaquoggio.bid
        description: Pasta al salame?
        server: server-docker
        container: mealie
        statusStyle: "dot"
        showStats: true

    - Docling:
        icon: sh-docling.png
        href: http://quoggioserver:5001
        description: convertitore documenti
        server: server-docker
        container: docling
        statusStyle: "dot"
        showStats: true

    # - Vikunja:
    #     icon: vikunja.png
    #     href: https://vikunja.fantaquoggio.bid
    #     description: Cos'è questa aria da PM?
    #     server: server-docker
    #     container: vikunja
    #     statusStyle: "dot"
    #     showStats: true

    # - Actualtap:
    #     icon: actual-budget.png
    #     description: Actual integration with contactless payments
    #     server: server-docker
    #     container: actualtap-py
    #     statusStyle: "dot"
    #     showStats: true

- Arr:
    - Sonarr:
        icon: sonarr.png
        href: http://quoggioserver:8989
        description: Scarica serie tv
        server: server-docker
        container: sonarr
        statusStyle: "dot"
        showStats: true

    - Radarr:
        icon: radarr.png
        href: http://quoggioserver:7878
        description: Scarica film
        server: server-docker
        container: radarr
        statusStyle: "dot"
        showStats: true

    - Bazarr:
        icon: bazarr.png
        href: http://quoggioserver:6767
        description: THEBOAZAAARRR
        server: server-docker
        container: bazarr
        statusStyle: "dot"
        showStats: true

    - Jellyseerr:
        icon: jellyseerr.png
        href: http://quoggioserver:5055
        description: Chiedi e ti sarà dato
        server: server-docker
        container: jellyseerr
        statusStyle: "dot"
        showStats: true

    - Prowlarr:
        icon: prowlarr.png
        href: http://quoggioserver:9696
        description: Lo smistatore
        server: server-docker
        container: prowlarr
        statusStyle: "dot"
        showStats: true

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.fantaquoggio.bid
        description: Pezzotto
        server: server-docker
        container: jellyfin
        statusStyle: "dot"
        showStats: true

    - Audiobookshelf:
        icon: audiobookshelf.png
        href: https://audiobookshelf.fantaquoggio.bid
        description: Pezzotto per (audio)libri 
        server: server-docker
        container: audiobookshelf
        statusStyle: "dot"
        showStats: true

- AI:
    - Open-webui:
        icon: open-webui.png
        href: https://chat.fantaquoggio.bid
        description: Chatroulette
        server: server-docker
        container: openwebui
        statusStyle: "dot"
        showStats: true

    - MCP Server:
        icon: sh-investbrain
        # href: https://chat.fantaquoggio.bid
        description: Magi
        server: server-docker
        container: mymcp
        statusStyle: "dot"
        showStats: true
