title: Home is where Quoggio is
# startUrl: https://custom.url
background:
  image: /images/bg.png
  blur: xs
  opacity: 40
color: zinc
useEqualHeights: true
theme: dark # or light
# statusStyle: "dot"
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google
layout:
  Utilities:
    style: row
    columns: 4
