- greeting:
    text_size: xl
    text: Home is where Quoggio is

- openmeteo:
    label: Lainate
    latitude: 45.569025
    longitude: 9.029508
    timezone: Europe/Rome
    units: metric
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _blank # One of _self, _blank, _parent or _top
