
username: quoghs
password: "{{ VAULT_PASSWORD }}"
ssh_public_key: "{{ SSH_PUBLIC_KEY }}"

ghcr_username: "chquaggio"
ghcr_token: "{{ GH_TOKEN }}"

bazarr_key: "{{ BAZARR_KEY }}"
beszel_user: "{{ BESZEL_USER }}"
beszel_password: "{{ BESZEL_PASSWORD }}"
beszel_sid: "{{ BESZEL_SID }}"
jellyfin_key: "{{ JELLYFIN_KEY }}"
jellyseerr_key: "{{ JELLYSEERR_KEY }}"
mealie_key: "{{ MEALIE_KEY }}"
pihole_password: "{{ PIHOLE_PASSWORD }}"
prowlarr_key: "{{ PROWLARR_KEY }}"
qb_user: "{{ QB_USER }}"
qb_password: "{{ QB_PASSWORD }}"
radarr_key: "{{ RADARR_KEY }}"
sonarr_key: "{{ SONARR_KEY }}"
trilium_token: "{{ TRILIUM_TOKEN }}"
trilium_url: "{{ TRILIUM_BASE_URL_PROD }}"

cf_token: "{{ CF_TOKEN }}"

shell: /usr/bin/zsh

dotfiles_repo: https://github.com/chquaggio/dotfiles

docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

extra_packages:
  - curl
  - wget
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gnupg
  - bat
  - fzf
  - ripgrep
  - fd-find
  - smartmontools
