
username: quoghs
password: "{{ VAULT_PASSWORD }}"
ssh_public_key: "{{ SSH_PUBLIC_KEY }}"

ghcr_username: "chquaggio"
ghcr_token: "{{ GH_TOKEN }}"

shell: /usr/bin/zsh

dotfiles_repo: https://github.com/chquaggio/dotfiles

docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

extra_packages:
  - curl
  - wget
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gnupg
  - bat
  - fzf
  - ripgrep
  - fd-find
