---
- name: Configure mymcp service
  set_fact:
    mymcp_service:
      name: mymcp
      image: ghcr.io/chquaggio/mymcp:latest
      container_name: mymcp
      restart: unless-stopped
      ports:
        - 7000:7000
      networks:
        - proxy-network
