---
- name: Configure mymcp service
  set_fact:
    mymcp_service:
      name: mymcp
      image: ghcr.io/chquaggio/mymcp:latest
      container_name: mymcp
      restart: unless-stopped
      environment:
        - TRILIUM_TOKEN={{ trilium_token }}
        - TRILIUM_BASE_URL_PROD={{ trilium_url }}
        - ACTUAL_URL={{ actual_url }}
        - ACTUAL_PASSWORD={{ actual_password }}
        - ACTUAL_BUDGET={{ actual_budget }}
      ports:
        - 7000:7000
      networks:
        - qnet
